
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/testdb_spring?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "0000"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 792037345123-bk9hgdf72vo5d3g5e996j36go814uhs1.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 2GB
      max-request-size: 2GB
  redis:
    database: 0
    port: 6379
    lettuce:
    timeout: 5000000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000000 # 原来的3600000 * 100
      cache-null-values: true
    default:
      expire-time: 200000000 # 原来的200 * 1000000
    user:
      expire-time: 180000000 # 原来的180 * 1000000
    file:
      expire-time: 180000000 # 原来的180 * 1000000
      filename: test
  data:
    mongodb:
      uri: mongodb://root:0000@localhost:27017/chatdb?authSource=admin

    redis:
      host: localhost
  artemis:
    embedded:
      data-directory:


bezkoder:
  app:
    jwtCookieName: sendEveryThing
    jwtRefreshCookieName: sendEveryThingRefresh
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
    jwtExpirationRefreshMs: 172800000

  filebase:
    AccessKeyId: 9D950C2D6B3E6F122289
    SecretAccessKey: d24dhf1z9Fj6jd6Cn7A2u4u62Xnjh3Z09RvUQsxl
    endpoint: https://s3.filebase.com
server:
  port: 8088


